name: beam
description: Best Events Around Me
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  auto_route: ^5.0.4
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.4.3
  firebase_core: ^2.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.3
  hydrated_bloc: ^9.1.0
  image_card: ^0.0.4
  intl: ^0.18.0
  json_annotation: ^4.8.0
  path_provider: ^2.0.13

dev_dependencies:
  auto_route_generator: ^5.0.3
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
